// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_incnice 22
#define SYS_decnice 23
#define SYS_sched  24
#define SYS_lwp_create 25
#define SYS_lwp_join 26
#define SYS_sched_name 27
#define SYS_dsstore 28
#define SYS_dsrestart 29
#define SYS_atom_add 30
#define SYS_atom_sub 31
#define SYS_atom_mul 32
#define SYS_atom_div 33
#define SYS_atom_mod 34
#define SYS_atom_set 35
#define SYS_atom_swp 36
#define SYS_sem_init 37
#define SYS_sem_p    38
#define SYS_sem_v    39
#define SYS_mut_init 40
#define SYS_mut_p    41
#define SYS_mut_v    42
